/**
 * R6 — external remedial video search via the official YouTube Data API v3.
 *
 * SERVER ONLY. The API key is read from `process.env.YOUTUBE_API_KEY` (never
 * `VITE_`, never sent to the browser). When the key is missing, quota is
 * exhausted, or the upstream errors/times out, this returns `[]` — the caller
 * then shows no video card. It NEVER invents results.
 *
 * Every returned candidate is a REAL search hit: a real 11-char video id, a
 * real snippet title/channel, and (from a second `videos.list` call) the real
 * duration + the provider's `status.embeddable` flag. Nothing here is
 * generated by an LLM.
 */

import { parseIso8601Duration, YOUTUBE_ID_RE } from "@/lib/remedial-video";
import type { VideoCandidate } from "@/lib/remedial-video-ranking";

const SEARCH_URL = "https://www.googleapis.com/youtube/v3/search";
const VIDEOS_URL = "https://www.googleapis.com/youtube/v3/videos";
const TIMEOUT_MS = 6_000;
/** Small candidate set — conserves the 10k/day quota (search = 100 units). */
export const YOUTUBE_SEARCH_MAX_RESULTS = 5;

function timeoutSignal(ms: number): AbortSignal {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  (timer as unknown as { unref?: () => void }).unref?.();
  return controller.signal;
}

type SearchListResponse = {
  items?: { id?: { videoId?: string }; snippet?: { title?: string; channelTitle?: string } }[];
};
type VideosListResponse = {
  items?: {
    id?: string;
    contentDetails?: { duration?: string };
    status?: { embeddable?: boolean; privacyStatus?: string; uploadStatus?: string };
    snippet?: { title?: string; channelTitle?: string; description?: string };
  }[];
};

export function youtubeApiConfigured(): boolean {
  return !!(process.env.YOUTUBE_API_KEY && process.env.YOUTUBE_API_KEY.trim());
}

/**
 * Returns real, embeddable YouTube candidates for `query`, or `[]`. Two calls:
 * search.list for ids, then videos.list for duration + embeddable status
 * (search snippets don't carry either).
 */
export async function searchYouTubeVideos(query: string): Promise<VideoCandidate[]> {
  const key = process.env.YOUTUBE_API_KEY?.trim();
  if (!key || !query.trim()) return [];

  try {
    const searchParams = new URLSearchParams({
      key,
      part: "snippet",
      type: "video",
      q: query.trim().slice(0, 200),
      maxResults: String(YOUTUBE_SEARCH_MAX_RESULTS),
      videoEmbeddable: "true",
      safeSearch: "strict",
      relevanceLanguage: "en",
    });
    const searchRes = await fetch(`${SEARCH_URL}?${searchParams}`, {
      signal: timeoutSignal(TIMEOUT_MS),
      headers: { accept: "application/json" },
    });
    if (!searchRes.ok) {
      console.error(`[searchYouTubeVideos] search.list ${searchRes.status}`);
      return [];
    }
    const search = (await searchRes.json()) as SearchListResponse;
    const ids = (search.items ?? [])
      .map((it) => it.id?.videoId)
      .filter((id): id is string => !!id && YOUTUBE_ID_RE.test(id));
    if (ids.length === 0) return [];

    const videoParams = new URLSearchParams({
      key,
      part: "snippet,contentDetails,status",
      id: ids.join(","),
      maxResults: String(ids.length),
    });
    const videosRes = await fetch(`${VIDEOS_URL}?${videoParams}`, {
      signal: timeoutSignal(TIMEOUT_MS),
      headers: { accept: "application/json" },
    });
    if (!videosRes.ok) {
      console.error(`[searchYouTubeVideos] videos.list ${videosRes.status}`);
      return [];
    }
    const details = (await videosRes.json()) as VideosListResponse;

    const out: VideoCandidate[] = [];
    for (const item of details.items ?? []) {
      const id = item.id;
      if (!id || !YOUTUBE_ID_RE.test(id)) continue;
      if (item.status?.embeddable === false) continue;
      if (item.status?.privacyStatus && item.status.privacyStatus !== "public") continue;
      const title = (item.snippet?.title ?? "").trim();
      if (!title) continue;
      out.push({
        videoId: id,
        title,
        channelTitle: (item.snippet?.channelTitle ?? "").trim() || undefined,
        description: (item.snippet?.description ?? "").trim().slice(0, 600),
        durationSeconds: parseIso8601Duration(item.contentDetails?.duration) ?? undefined,
        embeddable: true,
      });
    }
    // preserve search relevance order
    const rank = new Map(ids.map((id, i) => [id, i]));
    out.sort((a, b) => (rank.get(a.videoId) ?? 99) - (rank.get(b.videoId) ?? 99));
    return out;
  } catch (e) {
    console.error(`[searchYouTubeVideos] failed: ${e instanceof Error ? e.message : String(e)}`);
    return [];
  }
}

/** The educational search query for a Study Path topic + weak concepts. */
export function buildVideoSearchQuery(input: {
  topicTitle: string;
  weakConcepts: string[];
}): string {
  const concepts = input.weakConcepts.slice(0, 3).join(" ");
  return `${input.topicTitle} ${concepts} explained tutorial`.replace(/\s+/g, " ").trim();
}
