-- ============================================================================
--  CSM Demo Course — Testing Only   ·   DELETE / TEARDOWN
-- ============================================================================
--  Removes the demo course created by create_csm_demo_course.sql and EVERY row
--  that depends on it — including data generated by testers while using it
--  (enrollments, quiz attempts, answers, progress, study paths, remedial
--  learning interactions, AI tutor conversations, notifications, study-time
--  sessions).
--
--  SAFETY PROPERTIES
--    * Targets ONLY the fixed demo course UUID
--        de300000-0000-4000-a000-000000000000
--      and rows reachable from it. There is NO title / slug / "LIKE" matching.
--    * Does NOT touch any other course or any student data that belongs to
--      another course. A tester's account, profile, role, VARK profile and
--      learning preferences are NOT affected (those are per-user, not
--      per-course).
--    * Deletes children before parents in an order derived from the ACTUAL
--      foreign keys (verified against supabase/bootstrap_new_project.sql),
--      not from an assumption that ON DELETE CASCADE is configured. Most of
--      these FKs *are* ON DELETE CASCADE, but a few are not:
--         - study_sessions.course_id            -> ON DELETE SET NULL
--         - ai_conversations.topic_id           -> ON DELETE SET NULL
--         - lecturer_slots.course_id            -> ON DELETE RESTRICT
--      so those are handled explicitly here.
--    * Runs in ONE transaction. The deferred constraint triggers
--      trg_topic_has_questions / trg_course_quiz_has_questions are checked at
--      COMMIT, by which point the parent topic / course_quiz rows are already
--      gone, so they are correctly skipped.
--
--  HOW TO RUN: paste into the Supabase SQL Editor and run once (top to bottom).
--  Idempotent: running it again when the course is already gone is a no-op.
-- ============================================================================

begin;

do $$
declare
  v_course uuid := 'de300000-0000-4000-a000-000000000000';

  -- id sets, captured up front while every parent table still exists
  v_topics       uuid[];
  v_lessons      uuid[];
  v_course_quiz  uuid[];
  v_questions    uuid[];
  v_attempts     uuid[];
  v_study_paths  uuid[];
  v_conversations uuid[];

  n bigint;
begin
  -- Nothing to do if the demo course is not present.
  if not exists (select 1 from public.courses where id = v_course) then
    raise notice 'CSM Demo Course (%) not found — nothing to delete.', v_course;
    return;
  end if;

  -- lecturer_slots.course_id is ON DELETE RESTRICT, so any slot bound to the
  -- demo course must be removed before the course. By default the create script
  -- binds NO slot; this only matters if its optional "lecturer analytics" block
  -- was enabled. Deleting the slot does NOT revert a tester account that already
  -- claimed it from role 'teacher' — that is per-user data and is left alone;
  -- a notice is raised so the operator knows.
  if exists (select 1 from public.lecturer_slots where course_id = v_course and claimed_by is not null) then
    raise notice 'NOTE: a lecturer slot for the demo course was claimed. The tester account keeps role ''teacher'' (per-user data, not touched here).';
  end if;
  delete from public.lecturer_slots where course_id = v_course;
  get diagnostics n = row_count;
  if n > 0 then raise notice '  lecturer_slots: %', n; end if;

  select coalesce(array_agg(id), '{}'::uuid[]) into v_topics
    from public.topics where course_id = v_course;

  select coalesce(array_agg(id), '{}'::uuid[]) into v_lessons
    from public.lessons where topic_id = any(v_topics);

  select coalesce(array_agg(id), '{}'::uuid[]) into v_course_quiz
    from public.course_quizzes where course_id = v_course;

  select coalesce(array_agg(id), '{}'::uuid[]) into v_questions
    from public.questions
    where topic_id = any(v_topics) or course_quiz_id = any(v_course_quiz);

  select coalesce(array_agg(id), '{}'::uuid[]) into v_attempts
    from public.quiz_attempts
    where topic_id = any(v_topics) or course_quiz_id = any(v_course_quiz);

  select coalesce(array_agg(id), '{}'::uuid[]) into v_study_paths
    from public.study_paths
    where course_id = v_course
       or topic_id = any(v_topics)
       or attempt_id = any(v_attempts);

  select coalesce(array_agg(id), '{}'::uuid[]) into v_conversations
    from public.ai_conversations
    where course_id = v_course or topic_id = any(v_topics);

  raise notice 'CSM demo teardown: % topic(s), % lesson(s), % course-quiz, % question(s), % attempt(s), % study path(s), % conversation(s).',
    array_length(v_topics, 1), array_length(v_lessons, 1), array_length(v_course_quiz, 1),
    array_length(v_questions, 1), array_length(v_attempts, 1), array_length(v_study_paths, 1),
    array_length(v_conversations, 1);

  -- 1. enrollments — remove first so the questions-delete notification trigger
  --    (trg_notify_quiz_updated) finds no recipients and re-creates nothing.
  delete from public.enrollments where course_id = v_course;
  get diagnostics n = row_count; raise notice '  enrollments: %', n;

  -- 2. learning_interactions — FK to course/topic/lesson/attempt/study_path
  delete from public.learning_interactions
   where course_id = v_course
      or topic_id       = any(v_topics)
      or lesson_id       = any(v_lessons)
      or quiz_attempt_id = any(v_attempts)
      or study_path_id   = any(v_study_paths);
  get diagnostics n = row_count; raise notice '  learning_interactions: %', n;

  -- 3. attempt_answers — FK to quiz_attempts + questions
  delete from public.attempt_answers
   where attempt_id  = any(v_attempts)
      or question_id = any(v_questions);
  get diagnostics n = row_count; raise notice '  attempt_answers: %', n;

  -- 4. study_paths — FK to course/topic/attempt (learning_interactions already gone)
  delete from public.study_paths where id = any(v_study_paths);
  get diagnostics n = row_count; raise notice '  study_paths: %', n;

  -- 5. quiz_attempts — FK to topic / course_quiz
  delete from public.quiz_attempts where id = any(v_attempts);
  get diagnostics n = row_count; raise notice '  quiz_attempts: %', n;

  -- 6. progress — FK to lessons
  delete from public.progress where lesson_id = any(v_lessons);
  get diagnostics n = row_count; raise notice '  progress: %', n;

  -- 7. ai_messages — FK to ai_conversations
  delete from public.ai_messages where conversation_id = any(v_conversations);
  get diagnostics n = row_count; raise notice '  ai_messages: %', n;

  -- 8. ai_conversations — FK to course (cascade) + topic (set null)
  delete from public.ai_conversations where id = any(v_conversations);
  get diagnostics n = row_count; raise notice '  ai_conversations: %', n;

  -- 9. study_sessions — FK to course is ON DELETE SET NULL, so delete explicitly
  delete from public.study_sessions where course_id = v_course;
  get diagnostics n = row_count; raise notice '  study_sessions: %', n;

  -- 10. questions — FK to topic / course_quiz. Deferred "must keep >=1 question"
  --     triggers are checked at COMMIT, after the parents are gone (steps 12-13).
  delete from public.questions where id = any(v_questions);
  get diagnostics n = row_count; raise notice '  questions: %', n;

  -- 11. notifications — FK to course/topic/quiz. Safe now: no more question
  --     deletes to re-create any, and enrollments are already gone.
  delete from public.notifications
   where course_id = v_course
      or topic_id = any(v_topics)
      or quiz_id  = any(v_course_quiz);
  get diagnostics n = row_count; raise notice '  notifications: %', n;

  -- 12. lessons — FK to topic
  delete from public.lessons where id = any(v_lessons);
  get diagnostics n = row_count; raise notice '  lessons: %', n;

  -- 13. course_quizzes — FK to course
  delete from public.course_quizzes where id = any(v_course_quiz);
  get diagnostics n = row_count; raise notice '  course_quizzes: %', n;

  -- 14. topics — FK to course
  delete from public.topics where id = any(v_topics);
  get diagnostics n = row_count; raise notice '  topics: %', n;

  -- 15. the course itself
  delete from public.courses where id = v_course;
  get diagnostics n = row_count; raise notice '  courses: %', n;
end $$;

-- ----------------------------------------------------------------------------
-- Verification — every one of these MUST be 0, or the transaction aborts.
-- ----------------------------------------------------------------------------
do $$
declare
  v_course uuid := 'de300000-0000-4000-a000-000000000000';
  v_leftover bigint;
begin
  select
      (select count(*) from public.courses        where id = v_course)
    + (select count(*) from public.topics         where course_id = v_course)
    + (select count(*) from public.course_quizzes where course_id = v_course)
    + (select count(*) from public.enrollments    where course_id = v_course)
    + (select count(*) from public.notifications  where course_id = v_course)
    + (select count(*) from public.study_paths    where course_id = v_course)
    + (select count(*) from public.ai_conversations where course_id = v_course)
    + (select count(*) from public.learning_interactions where course_id = v_course)
    + (select count(*) from public.study_sessions where course_id = v_course)
    + (select count(*) from public.lecturer_slots where course_id = v_course)
    -- transitively-scoped tables (must also be empty of demo rows)
    + (select count(*) from public.lessons l
         where l.topic_id in (select id from public.topics where course_id = v_course))
    + (select count(*) from public.questions q
         where q.topic_id in (select id from public.topics where course_id = v_course)
            or q.course_quiz_id in (select id from public.course_quizzes where course_id = v_course))
    + (select count(*) from public.quiz_attempts a
         where a.topic_id in (select id from public.topics where course_id = v_course)
            or a.course_quiz_id in (select id from public.course_quizzes where course_id = v_course))
    into v_leftover;

  if v_leftover <> 0 then
    raise exception 'CSM demo teardown incomplete: % row(s) still reference the demo course.', v_leftover;
  end if;
  raise notice 'CSM Demo Course fully removed. No demo rows remain.';
end $$;

commit;

-- ============================================================================
--  Done. "CSM Demo Course — Testing Only" and all data derived from it are
--  gone. Per-user records (accounts, profiles, roles, VARK profiles, learning
--  preferences) were intentionally left untouched.
-- ============================================================================
