/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LecturerRouteImport } from './routes/lecturer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LecturerIndexRouteImport } from './routes/lecturer.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as TeachersAuthRouteImport } from './routes/teachers.auth'
import { Route as LecturerStudentsRouteImport } from './routes/lecturer.students'
import { Route as LecturerPerformanceRouteImport } from './routes/lecturer.performance'
import { Route as LecturerNotificationsRouteImport } from './routes/lecturer.notifications'
import { Route as LecturerMaterialsRouteImport } from './routes/lecturer.materials'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyCoursesRouteImport } from './routes/_authenticated/my-courses'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as LecturerQuizzesIndexRouteImport } from './routes/lecturer.quizzes.index'
import { Route as LecturerQuizzesTopicIdRouteImport } from './routes/lecturer.quizzes.$topicId'
import { Route as AuthenticatedTopicTopicIdRouteImport } from './routes/_authenticated/topic.$topicId'
import { Route as AuthenticatedStudyPathCourseIdRouteImport } from './routes/_authenticated/study-path.$courseId'
import { Route as AuthenticatedResultAttemptIdRouteImport } from './routes/_authenticated/result.$attemptId'
import { Route as AuthenticatedQuizzesCourseIdRouteImport } from './routes/_authenticated/quizzes.$courseId'
import { Route as AuthenticatedQuizTopicIdRouteImport } from './routes/_authenticated/quiz.$topicId'
import { Route as AuthenticatedPerformanceCourseIdRouteImport } from './routes/_authenticated/performance.$courseId'
import { Route as AuthenticatedOnboardingPreferencesRouteImport } from './routes/_authenticated/onboarding.preferences'
import { Route as AuthenticatedLearningStudyPathIdRouteImport } from './routes/_authenticated/learning.$studyPathId'
import { Route as AuthenticatedCourseQuizQuizIdRouteImport } from './routes/_authenticated/course-quiz.$quizId'
import { Route as LecturerQuizzesGeneralNewRouteImport } from './routes/lecturer.quizzes.general.new'
import { Route as LecturerQuizzesGeneralQuizIdRouteImport } from './routes/lecturer.quizzes.general.$quizId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRoute = LecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerIndexRoute = LecturerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LecturerRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersAuthRoute = TeachersAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => TeachersRoute,
} as any)
const LecturerStudentsRoute = LecturerStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerPerformanceRoute = LecturerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerNotificationsRoute = LecturerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerMaterialsRoute = LecturerMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => LecturerRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyCoursesRoute = AuthenticatedMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LecturerQuizzesIndexRoute = LecturerQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerQuizzesTopicIdRoute = LecturerQuizzesTopicIdRouteImport.update({
  id: '/quizzes/$topicId',
  path: '/quizzes/$topicId',
  getParentRoute: () => LecturerRoute,
} as any)
const AuthenticatedTopicTopicIdRoute =
  AuthenticatedTopicTopicIdRouteImport.update({
    id: '/topic/$topicId',
    path: '/topic/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudyPathCourseIdRoute =
  AuthenticatedStudyPathCourseIdRouteImport.update({
    id: '/study-path/$courseId',
    path: '/study-path/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultAttemptIdRoute =
  AuthenticatedResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizzesCourseIdRoute =
  AuthenticatedQuizzesCourseIdRouteImport.update({
    id: '/quizzes/$courseId',
    path: '/quizzes/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizTopicIdRoute =
  AuthenticatedQuizTopicIdRouteImport.update({
    id: '/quiz/$topicId',
    path: '/quiz/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerformanceCourseIdRoute =
  AuthenticatedPerformanceCourseIdRouteImport.update({
    id: '/performance/$courseId',
    path: '/performance/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingPreferencesRoute =
  AuthenticatedOnboardingPreferencesRouteImport.update({
    id: '/onboarding/preferences',
    path: '/onboarding/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearningStudyPathIdRoute =
  AuthenticatedLearningStudyPathIdRouteImport.update({
    id: '/learning/$studyPathId',
    path: '/learning/$studyPathId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCourseQuizQuizIdRoute =
  AuthenticatedCourseQuizQuizIdRouteImport.update({
    id: '/course-quiz/$quizId',
    path: '/course-quiz/$quizId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LecturerQuizzesGeneralNewRoute =
  LecturerQuizzesGeneralNewRouteImport.update({
    id: '/quizzes/general/new',
    path: '/quizzes/general/new',
    getParentRoute: () => LecturerRoute,
  } as any)
const LecturerQuizzesGeneralQuizIdRoute =
  LecturerQuizzesGeneralQuizIdRouteImport.update({
    id: '/quizzes/general/$quizId',
    path: '/quizzes/general/$quizId',
    getParentRoute: () => LecturerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/terms': typeof TermsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/notifications': typeof LecturerNotificationsRoute
  '/lecturer/performance': typeof LecturerPerformanceRoute
  '/lecturer/students': typeof LecturerStudentsRoute
  '/teachers/auth': typeof TeachersAuthRoute
  '/courses/': typeof CoursesIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/course-quiz/$quizId': typeof AuthenticatedCourseQuizQuizIdRoute
  '/learning/$studyPathId': typeof AuthenticatedLearningStudyPathIdRoute
  '/onboarding/preferences': typeof AuthenticatedOnboardingPreferencesRoute
  '/performance/$courseId': typeof AuthenticatedPerformanceCourseIdRoute
  '/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/quizzes/$courseId': typeof AuthenticatedQuizzesCourseIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/study-path/$courseId': typeof AuthenticatedStudyPathCourseIdRoute
  '/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
  '/lecturer/quizzes/$topicId': typeof LecturerQuizzesTopicIdRoute
  '/lecturer/quizzes/': typeof LecturerQuizzesIndexRoute
  '/lecturer/quizzes/general/$quizId': typeof LecturerQuizzesGeneralQuizIdRoute
  '/lecturer/quizzes/general/new': typeof LecturerQuizzesGeneralNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/terms': typeof TermsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/notifications': typeof LecturerNotificationsRoute
  '/lecturer/performance': typeof LecturerPerformanceRoute
  '/lecturer/students': typeof LecturerStudentsRoute
  '/teachers/auth': typeof TeachersAuthRoute
  '/courses': typeof CoursesIndexRoute
  '/lecturer': typeof LecturerIndexRoute
  '/course-quiz/$quizId': typeof AuthenticatedCourseQuizQuizIdRoute
  '/learning/$studyPathId': typeof AuthenticatedLearningStudyPathIdRoute
  '/onboarding/preferences': typeof AuthenticatedOnboardingPreferencesRoute
  '/performance/$courseId': typeof AuthenticatedPerformanceCourseIdRoute
  '/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/quizzes/$courseId': typeof AuthenticatedQuizzesCourseIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/study-path/$courseId': typeof AuthenticatedStudyPathCourseIdRoute
  '/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
  '/lecturer/quizzes/$topicId': typeof LecturerQuizzesTopicIdRoute
  '/lecturer/quizzes': typeof LecturerQuizzesIndexRoute
  '/lecturer/quizzes/general/$quizId': typeof LecturerQuizzesGeneralQuizIdRoute
  '/lecturer/quizzes/general/new': typeof LecturerQuizzesGeneralNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/my-courses': typeof AuthenticatedMyCoursesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/notifications': typeof LecturerNotificationsRoute
  '/lecturer/performance': typeof LecturerPerformanceRoute
  '/lecturer/students': typeof LecturerStudentsRoute
  '/teachers/auth': typeof TeachersAuthRoute
  '/courses/': typeof CoursesIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/_authenticated/course-quiz/$quizId': typeof AuthenticatedCourseQuizQuizIdRoute
  '/_authenticated/learning/$studyPathId': typeof AuthenticatedLearningStudyPathIdRoute
  '/_authenticated/onboarding/preferences': typeof AuthenticatedOnboardingPreferencesRoute
  '/_authenticated/performance/$courseId': typeof AuthenticatedPerformanceCourseIdRoute
  '/_authenticated/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/_authenticated/quizzes/$courseId': typeof AuthenticatedQuizzesCourseIdRoute
  '/_authenticated/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/_authenticated/study-path/$courseId': typeof AuthenticatedStudyPathCourseIdRoute
  '/_authenticated/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
  '/lecturer/quizzes/$topicId': typeof LecturerQuizzesTopicIdRoute
  '/lecturer/quizzes/': typeof LecturerQuizzesIndexRoute
  '/lecturer/quizzes/general/$quizId': typeof LecturerQuizzesGeneralQuizIdRoute
  '/lecturer/quizzes/general/new': typeof LecturerQuizzesGeneralNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/lecturer'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/teachers'
    | '/terms'
    | '/about'
    | '/analytics'
    | '/dashboard'
    | '/games'
    | '/my-courses'
    | '/notifications'
    | '/profile'
    | '/security'
    | '/settings'
    | '/auth/callback'
    | '/auth/google'
    | '/courses/$slug'
    | '/lecturer/materials'
    | '/lecturer/notifications'
    | '/lecturer/performance'
    | '/lecturer/students'
    | '/teachers/auth'
    | '/courses/'
    | '/lecturer/'
    | '/course-quiz/$quizId'
    | '/learning/$studyPathId'
    | '/onboarding/preferences'
    | '/performance/$courseId'
    | '/quiz/$topicId'
    | '/quizzes/$courseId'
    | '/result/$attemptId'
    | '/study-path/$courseId'
    | '/topic/$topicId'
    | '/lecturer/quizzes/$topicId'
    | '/lecturer/quizzes/'
    | '/lecturer/quizzes/general/$quizId'
    | '/lecturer/quizzes/general/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/teachers'
    | '/terms'
    | '/about'
    | '/analytics'
    | '/dashboard'
    | '/games'
    | '/my-courses'
    | '/notifications'
    | '/profile'
    | '/security'
    | '/settings'
    | '/auth/callback'
    | '/auth/google'
    | '/courses/$slug'
    | '/lecturer/materials'
    | '/lecturer/notifications'
    | '/lecturer/performance'
    | '/lecturer/students'
    | '/teachers/auth'
    | '/courses'
    | '/lecturer'
    | '/course-quiz/$quizId'
    | '/learning/$studyPathId'
    | '/onboarding/preferences'
    | '/performance/$courseId'
    | '/quiz/$topicId'
    | '/quizzes/$courseId'
    | '/result/$attemptId'
    | '/study-path/$courseId'
    | '/topic/$topicId'
    | '/lecturer/quizzes/$topicId'
    | '/lecturer/quizzes'
    | '/lecturer/quizzes/general/$quizId'
    | '/lecturer/quizzes/general/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/lecturer'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/teachers'
    | '/terms'
    | '/_authenticated/about'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/games'
    | '/_authenticated/my-courses'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/auth/google'
    | '/courses/$slug'
    | '/lecturer/materials'
    | '/lecturer/notifications'
    | '/lecturer/performance'
    | '/lecturer/students'
    | '/teachers/auth'
    | '/courses/'
    | '/lecturer/'
    | '/_authenticated/course-quiz/$quizId'
    | '/_authenticated/learning/$studyPathId'
    | '/_authenticated/onboarding/preferences'
    | '/_authenticated/performance/$courseId'
    | '/_authenticated/quiz/$topicId'
    | '/_authenticated/quizzes/$courseId'
    | '/_authenticated/result/$attemptId'
    | '/_authenticated/study-path/$courseId'
    | '/_authenticated/topic/$topicId'
    | '/lecturer/quizzes/$topicId'
    | '/lecturer/quizzes/'
    | '/lecturer/quizzes/general/$quizId'
    | '/lecturer/quizzes/general/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  LecturerRoute: typeof LecturerRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TeachersRoute: typeof TeachersRouteWithChildren
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/': {
      id: '/lecturer/'
      path: '/'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof LecturerIndexRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/auth': {
      id: '/teachers/auth'
      path: '/auth'
      fullPath: '/teachers/auth'
      preLoaderRoute: typeof TeachersAuthRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/lecturer/students': {
      id: '/lecturer/students'
      path: '/students'
      fullPath: '/lecturer/students'
      preLoaderRoute: typeof LecturerStudentsRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/performance': {
      id: '/lecturer/performance'
      path: '/performance'
      fullPath: '/lecturer/performance'
      preLoaderRoute: typeof LecturerPerformanceRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/notifications': {
      id: '/lecturer/notifications'
      path: '/notifications'
      fullPath: '/lecturer/notifications'
      preLoaderRoute: typeof LecturerNotificationsRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/materials': {
      id: '/lecturer/materials'
      path: '/materials'
      fullPath: '/lecturer/materials'
      preLoaderRoute: typeof LecturerMaterialsRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-courses': {
      id: '/_authenticated/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof AuthenticatedMyCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lecturer/quizzes/': {
      id: '/lecturer/quizzes/'
      path: '/quizzes'
      fullPath: '/lecturer/quizzes/'
      preLoaderRoute: typeof LecturerQuizzesIndexRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/quizzes/$topicId': {
      id: '/lecturer/quizzes/$topicId'
      path: '/quizzes/$topicId'
      fullPath: '/lecturer/quizzes/$topicId'
      preLoaderRoute: typeof LecturerQuizzesTopicIdRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/_authenticated/topic/$topicId': {
      id: '/_authenticated/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof AuthenticatedTopicTopicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study-path/$courseId': {
      id: '/_authenticated/study-path/$courseId'
      path: '/study-path/$courseId'
      fullPath: '/study-path/$courseId'
      preLoaderRoute: typeof AuthenticatedStudyPathCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/result/$attemptId': {
      id: '/_authenticated/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes/$courseId': {
      id: '/_authenticated/quizzes/$courseId'
      path: '/quizzes/$courseId'
      fullPath: '/quizzes/$courseId'
      preLoaderRoute: typeof AuthenticatedQuizzesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$topicId': {
      id: '/_authenticated/quiz/$topicId'
      path: '/quiz/$topicId'
      fullPath: '/quiz/$topicId'
      preLoaderRoute: typeof AuthenticatedQuizTopicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance/$courseId': {
      id: '/_authenticated/performance/$courseId'
      path: '/performance/$courseId'
      fullPath: '/performance/$courseId'
      preLoaderRoute: typeof AuthenticatedPerformanceCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/preferences': {
      id: '/_authenticated/onboarding/preferences'
      path: '/onboarding/preferences'
      fullPath: '/onboarding/preferences'
      preLoaderRoute: typeof AuthenticatedOnboardingPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learning/$studyPathId': {
      id: '/_authenticated/learning/$studyPathId'
      path: '/learning/$studyPathId'
      fullPath: '/learning/$studyPathId'
      preLoaderRoute: typeof AuthenticatedLearningStudyPathIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/course-quiz/$quizId': {
      id: '/_authenticated/course-quiz/$quizId'
      path: '/course-quiz/$quizId'
      fullPath: '/course-quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedCourseQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lecturer/quizzes/general/new': {
      id: '/lecturer/quizzes/general/new'
      path: '/quizzes/general/new'
      fullPath: '/lecturer/quizzes/general/new'
      preLoaderRoute: typeof LecturerQuizzesGeneralNewRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/quizzes/general/$quizId': {
      id: '/lecturer/quizzes/general/$quizId'
      path: '/quizzes/general/$quizId'
      fullPath: '/lecturer/quizzes/general/$quizId'
      preLoaderRoute: typeof LecturerQuizzesGeneralQuizIdRouteImport
      parentRoute: typeof LecturerRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedMyCoursesRoute: typeof AuthenticatedMyCoursesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCourseQuizQuizIdRoute: typeof AuthenticatedCourseQuizQuizIdRoute
  AuthenticatedLearningStudyPathIdRoute: typeof AuthenticatedLearningStudyPathIdRoute
  AuthenticatedOnboardingPreferencesRoute: typeof AuthenticatedOnboardingPreferencesRoute
  AuthenticatedPerformanceCourseIdRoute: typeof AuthenticatedPerformanceCourseIdRoute
  AuthenticatedQuizTopicIdRoute: typeof AuthenticatedQuizTopicIdRoute
  AuthenticatedQuizzesCourseIdRoute: typeof AuthenticatedQuizzesCourseIdRoute
  AuthenticatedResultAttemptIdRoute: typeof AuthenticatedResultAttemptIdRoute
  AuthenticatedStudyPathCourseIdRoute: typeof AuthenticatedStudyPathCourseIdRoute
  AuthenticatedTopicTopicIdRoute: typeof AuthenticatedTopicTopicIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedMyCoursesRoute: AuthenticatedMyCoursesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCourseQuizQuizIdRoute: AuthenticatedCourseQuizQuizIdRoute,
  AuthenticatedLearningStudyPathIdRoute: AuthenticatedLearningStudyPathIdRoute,
  AuthenticatedOnboardingPreferencesRoute:
    AuthenticatedOnboardingPreferencesRoute,
  AuthenticatedPerformanceCourseIdRoute: AuthenticatedPerformanceCourseIdRoute,
  AuthenticatedQuizTopicIdRoute: AuthenticatedQuizTopicIdRoute,
  AuthenticatedQuizzesCourseIdRoute: AuthenticatedQuizzesCourseIdRoute,
  AuthenticatedResultAttemptIdRoute: AuthenticatedResultAttemptIdRoute,
  AuthenticatedStudyPathCourseIdRoute: AuthenticatedStudyPathCourseIdRoute,
  AuthenticatedTopicTopicIdRoute: AuthenticatedTopicTopicIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LecturerRouteChildren {
  LecturerMaterialsRoute: typeof LecturerMaterialsRoute
  LecturerNotificationsRoute: typeof LecturerNotificationsRoute
  LecturerPerformanceRoute: typeof LecturerPerformanceRoute
  LecturerStudentsRoute: typeof LecturerStudentsRoute
  LecturerIndexRoute: typeof LecturerIndexRoute
  LecturerQuizzesTopicIdRoute: typeof LecturerQuizzesTopicIdRoute
  LecturerQuizzesIndexRoute: typeof LecturerQuizzesIndexRoute
  LecturerQuizzesGeneralQuizIdRoute: typeof LecturerQuizzesGeneralQuizIdRoute
  LecturerQuizzesGeneralNewRoute: typeof LecturerQuizzesGeneralNewRoute
}

const LecturerRouteChildren: LecturerRouteChildren = {
  LecturerMaterialsRoute: LecturerMaterialsRoute,
  LecturerNotificationsRoute: LecturerNotificationsRoute,
  LecturerPerformanceRoute: LecturerPerformanceRoute,
  LecturerStudentsRoute: LecturerStudentsRoute,
  LecturerIndexRoute: LecturerIndexRoute,
  LecturerQuizzesTopicIdRoute: LecturerQuizzesTopicIdRoute,
  LecturerQuizzesIndexRoute: LecturerQuizzesIndexRoute,
  LecturerQuizzesGeneralQuizIdRoute: LecturerQuizzesGeneralQuizIdRoute,
  LecturerQuizzesGeneralNewRoute: LecturerQuizzesGeneralNewRoute,
}

const LecturerRouteWithChildren = LecturerRoute._addFileChildren(
  LecturerRouteChildren,
)

interface TeachersRouteChildren {
  TeachersAuthRoute: typeof TeachersAuthRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersAuthRoute: TeachersAuthRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  LecturerRoute: LecturerRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TeachersRoute: TeachersRouteWithChildren,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
