/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTopicTopicIdRouteImport } from './routes/_authenticated/topic.$topicId'
import { Route as AuthenticatedResultAttemptIdRouteImport } from './routes/_authenticated/result.$attemptId'
import { Route as AuthenticatedQuizTopicIdRouteImport } from './routes/_authenticated/quiz.$topicId'
import { Route as AuthenticatedOnboardingVarkRouteImport } from './routes/_authenticated/onboarding.vark'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTopicTopicIdRoute =
  AuthenticatedTopicTopicIdRouteImport.update({
    id: '/topic/$topicId',
    path: '/topic/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultAttemptIdRoute =
  AuthenticatedResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizTopicIdRoute =
  AuthenticatedQuizTopicIdRouteImport.update({
    id: '/quiz/$topicId',
    path: '/quiz/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingVarkRoute =
  AuthenticatedOnboardingVarkRouteImport.update({
    id: '/onboarding/vark',
    path: '/onboarding/vark',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/onboarding/vark': typeof AuthenticatedOnboardingVarkRoute
  '/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/onboarding/vark': typeof AuthenticatedOnboardingVarkRoute
  '/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/onboarding/vark': typeof AuthenticatedOnboardingVarkRoute
  '/_authenticated/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/_authenticated/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/_authenticated/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/analytics'
    | '/dashboard'
    | '/profile'
    | '/courses/$slug'
    | '/courses/'
    | '/onboarding/vark'
    | '/quiz/$topicId'
    | '/result/$attemptId'
    | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/analytics'
    | '/dashboard'
    | '/profile'
    | '/courses/$slug'
    | '/courses'
    | '/onboarding/vark'
    | '/quiz/$topicId'
    | '/result/$attemptId'
    | '/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/courses/$slug'
    | '/courses/'
    | '/_authenticated/onboarding/vark'
    | '/_authenticated/quiz/$topicId'
    | '/_authenticated/result/$attemptId'
    | '/_authenticated/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic/$topicId': {
      id: '/_authenticated/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof AuthenticatedTopicTopicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/result/$attemptId': {
      id: '/_authenticated/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$topicId': {
      id: '/_authenticated/quiz/$topicId'
      path: '/quiz/$topicId'
      fullPath: '/quiz/$topicId'
      preLoaderRoute: typeof AuthenticatedQuizTopicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/vark': {
      id: '/_authenticated/onboarding/vark'
      path: '/onboarding/vark'
      fullPath: '/onboarding/vark'
      preLoaderRoute: typeof AuthenticatedOnboardingVarkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedOnboardingVarkRoute: typeof AuthenticatedOnboardingVarkRoute
  AuthenticatedQuizTopicIdRoute: typeof AuthenticatedQuizTopicIdRoute
  AuthenticatedResultAttemptIdRoute: typeof AuthenticatedResultAttemptIdRoute
  AuthenticatedTopicTopicIdRoute: typeof AuthenticatedTopicTopicIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedOnboardingVarkRoute: AuthenticatedOnboardingVarkRoute,
  AuthenticatedQuizTopicIdRoute: AuthenticatedQuizTopicIdRoute,
  AuthenticatedResultAttemptIdRoute: AuthenticatedResultAttemptIdRoute,
  AuthenticatedTopicTopicIdRoute: AuthenticatedTopicTopicIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
