// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session

    // Proactively refresh the access token if it has expired (or is about to).
    // Otherwise an idle tab can attach a stale token and serverFn RPCs fail
    // with "JWT expired". Refresh with a 60s safety skew before sending.
    const nowWithSkew = Math.floor(Date.now() / 1000) + 60
    if (session && (!session.expires_at || session.expires_at <= nowWithSkew)) {
      const { data: refreshed, error } = await supabase.auth.refreshSession()
      if (refreshed.session) {
        session = refreshed.session
      } else {
        // Refresh failed (e.g. refresh token expired after a long idle).
        // Drop the stale session so we don't attach a dead token that the
        // server would reject with "JWT has expired".
        if (error) console.warn('[Supabase] session refresh failed:', error.message)
        session = null
      }
    }

    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
