// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// NOTE: errors are thrown as plain Error (not Response) — TanStack Start's
// seroval serializer cannot serialize a thrown Response, which reaches the
// client as an opaque "Seroval Error" with no message.
export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    // Prefer the Vite-injected values: they are statically replaced from the
    // current .env at build/dev time, so they always match the project the
    // browser client talks to. process.env can go stale — dotenv doesn't
    // override vars already set in a long-running dev process, so after the
    // Supabase project changed, tokens were validated against the OLD project
    // and every serverFn call failed with "Session expired".
    const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    const authHeader = request?.headers?.get("authorization");

    if (!authHeader?.startsWith("Bearer ")) {
      throw new Error("Please sign in to use this feature.");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Please sign in to use this feature.");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // NOTE: getUser(jwt) validates the token string directly (unlike
    // getClaims() which only reads from an internally stored session).
    // The server-side supabase client has persistSession: false so it
    // has no session — we must pass the token explicitly.
    let user;
    try {
      const { data, error } = await supabase.auth.getUser(token);
      if (error || !data?.user) {
        throw new Error("Session expired. Please sign in again.");
      }
      user = data.user;
    } catch {
      throw new Error("Session expired. Please sign in again.");
    }

    if (!user.id) {
      throw new Error("Session expired. Please sign in again.");
    }

    return next({
      context: {
        supabase,
        userId: user.id,
        claims: user.app_metadata,
      },
    });
  },
);
