// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "./client";

const REFRESH_SKEW_SECONDS = 60;
const REFRESH_FAILURE_COOLDOWN_MS = 30_000;

let refreshPromise: Promise<Session | null> | null = null;
let skipRefreshUntil = 0;

async function refreshSessionOnce() {
  const now = Date.now();
  if (now < skipRefreshUntil) return null;

  refreshPromise ??= supabase.auth
    .refreshSession()
    .then(({ data, error }) => {
      if (error) {
        skipRefreshUntil = Date.now() + REFRESH_FAILURE_COOLDOWN_MS;
        console.warn("[Supabase] session refresh failed:", error.message);
        return null;
      }

      return data.session;
    })
    .finally(() => {
      refreshPromise = null;
    });

  return refreshPromise;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    let session = data.session;

    // Proactively refresh the access token if it has expired (or is about to).
    // Burst serverFn calls share one refresh so Supabase's refresh-token
    // endpoint is not hammered with parallel requests. If the refresh fails,
    // fall back to the stale token so the server can reply with a clean
    // "Session expired" 401 instead of a missing-header error.
    const nowWithSkew = Math.floor(Date.now() / 1000) + REFRESH_SKEW_SECONDS;
    if (session && (!session.expires_at || session.expires_at <= nowWithSkew)) {
      session = (await refreshSessionOnce()) ?? session;
    }

    const token = session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
